from pydantic import BaseModel

class DevelopersWithIdSchemas(BaseModel):
    id: int 
    slug_game: str 
    name_game: str 
    plataform_id: int 
    plataform_name: str 
    plataform_slug: str 
    store_id: int 
    store_name: str 
    released_game: str 
    tba_game: bool 
    background_image_game: str 
    rating_game: float 
    rating_top_game: int 
    ratings_id: int 
    ratings_title: str 
    ratings_counts: str 
    ratings_percent: float 
    ratings_count: int 
    reviews_text_count: int 
    added: int 
    yet_add_by_status: int 
    owned_add_by_status: int 
    beaten_add_by_status: int 
    toplay_add_by_status: int 
    dropped_add_by_status: int 
    playing_add_by_status: int 
    metacritic: int 
    suggestions_count: int 
    updated: str 
    metacritic_id: int 
    metacritic_score: int 
    clip: bool
    tags_metacritic_id: int 
    tags_metacritic_name: str 
    tags_metacritic_slug: str 
    tags_metacritic_language: str 
    tags_games_count: int 
    tags_image_background: str 
    esrb_rating_id: int
    esrb_rating_name: str
    esrb_rating_slug: str 
    esrb_rating_name_en: str 
    esrb_rating_name_ru: str 
    user_game: str 
    reviews_count: int 
    saturated_color: str 
    dominant_color: str 
    short_screenshots_id: str 
    short_screenshots_image: str 
    parent_plataforms_id: int 
    parent_pataforms_name: str 
    parent_plataforms_slug: str 
    genres_id: int 
    genres_name: str 
    genres_slug: str

