"""create user model

Revision ID: 62c5a1aab719
Revises: 150064d67484
Create Date: 2023-11-12 17:18:00.679582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '62c5a1aab719'
down_revision = '150064d67484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ReleasedGamesLastMonth')
    op.drop_table('ReleasedGamesLastMonthPlataform')
    op.drop_index('ix_DevelopersWithId_id', table_name='DevelopersWithId')
    op.drop_table('DevelopersWithId')
    op.drop_table('migrations')
    op.drop_table('UpcomingGames')
    op.drop_table('Developers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Developers',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Developers_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('developer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('developer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exact_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('search_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('developer_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('top_games', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('games_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_background', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('score', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Developers_pkey')
    )
    op.create_table('UpcomingGames',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"UpcomingGames_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('slug_game', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name_game', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('playtime', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plataform_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plataform_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plataform_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='UpcomingGames_pkey')
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_8c82d7f526340ab734260ea46be')
    )
    op.create_table('DevelopersWithId',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"DevelopersWithId_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('slug_game', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name_game', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plataform_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plataform_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plataform_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('released_game', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tba_game', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('background_image_game', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rating_top_game', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ratings_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ratings_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ratings_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ratings_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviews_text_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('added', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yet_add_by_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owned_add_by_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('beaten_add_by_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('toplay_add_by_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dropped_add_by_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playing_add_by_status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metacritic', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('suggestions_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metacritic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('metacritic_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('tags_metacritic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tags_metacritic_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags_metacritic_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags_metacritic_language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags_games_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tags_image_background', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('esrb_rating_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('esrb_rating_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('esrb_rating_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('esrb_rating_name_en', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('esrb_rating_name_ru', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_game', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reviews_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saturated_color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dominant_color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('short_screenshots_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('short_screenshots_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_plataforms_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_plataforms_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_plataforms_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genres_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genres_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('genres_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('playtime', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('store_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ratings_counts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='DevelopersWithId_pkey')
    )
    op.create_index('ix_DevelopersWithId_id', 'DevelopersWithId', ['id'], unique=False)
    op.create_table('ReleasedGamesLastMonthPlataform',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ReleasedGamesLastMonthPlataform_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('slug_game', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name_game', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('playtime', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plataform_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plataform_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plataform_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ReleasedGamesLastMonthPlataform_pkey')
    )
    op.create_table('ReleasedGamesLastMonth',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ReleasedGamesLastMonth_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('plataform_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name_plataform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug_plataform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('games_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_background', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year_start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year_end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('game_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('game_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ReleasedGamesLastMonth_pkey')
    )
    # ### end Alembic commands ###
