"""add field in user

Revision ID: be80d7070f22
Revises: b140ac1b6aef
Create Date: 2023-11-12 21:35:15.506971

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'be80d7070f22'
down_revision = 'b140ac1b6aef'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('Users', 
                    sa.Column('id', sa.Integer, primary_key=True, index=True),
                    sa.Column('full_name', sa.String(length=340), nullable=False),
                    sa.Column('username', sa.String(length=120), nullable=False),
                    sa.Column('email', sa.String(length=240), nullable=False),
                    sa.Column('hashed_password', sa.String, nullable=False),
                    sa.Column('disabled', sa.Boolean, default=False),
                    sa.Column('created_at', sa.Date, default=datetime.now()))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
